# Voice Assistant Configuration

# Ollama Configuration
ollama:
  base_url: "http://localhost:11434"
  models:
    default: "llama3.2:3b"
    fast: "llama3.2:1b"
    large: "llama2:13b"
    mistral: "mistral:7b"

# Text-to-Speech Configuration
tts:
  model: "suno/bark-small"
  voice_preset: "v2/en_speaker_1"
  device: "auto"  # auto, cuda, cpu

# Speech-to-Text Configuration
stt:
  model: "base.en"
  language: "en"
  fp16: false  # Set to true if using GPU

# Audio Configuration
audio:
  sample_rate: 16000
  channels: 1
  dtype: "int16"

# Conversation Configuration
conversation:
  max_response_length: 20  # words
  memory_type: "buffer"
  verbose: false

# System Configuration
system:
  log_level: "INFO"
  log_file: "logs/voice_assistant.log"
